site_name: Embedded systems

theme:
  name: readthedocs
  logo: img/tux-logo.png

markdown_extensions:
  - admonition
  - pymdownx.superfences

extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - Raspberry Pi OS Labs:
    - Lab 1 - Setting-up Raspberry Pi OS Image:
      - image/lab1/intro.md
      - image/lab1/getting.md
      - image/lab1/mounting.md
      - image/lab1/increasing.md
      - image/lab1/modifying.md
      - image/lab1/executing.md
    - Lab 2 - Running the Raspberry Pi OS on a virtual machine on host:
      - image/lab2/intro.md
      - image/lab2/getting.md
      - image/lab2/installVM.md
      - image/lab2/using.md
    - Lab 3 - Setting-up and working with the Raspberry Pi OS without graphical user interface:
      - image/lab3/intro.md
      - image/lab3/writing.md
      - image/lab3/connecting.md
      - image/lab3/setting.md
      #- image/lab3/saving.md
  - QEMU:
    - image/qemu.md
  # - Docker:
  #   - docker